version: '3.0'
services:
  app_service:
    build:
      context: app-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  app_statistics:
    build:
      context: app-statistics
      dockerfile: Dockerfile
    ports:
      - "8090:8090"